
server:
  port: 8080
spring:
  application:
    name: Order Management Application
  datasource:
    url: jdbc:mysql://localhost:3306/fis-final?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true